'use strict';

// RunFlow Learning V1.
// Loaded before v9-engine-hook.js. It handles only learning/check-in routes and
// the V9 library duration policy, then delegates every other request.
const http=require('http');
const crypto=require('crypto');
const fs=require('fs');
const path=require('path');
const zlib=require('zlib');
const {URL}=require('url');

const SUPABASE_URL=String(process.env.SUPABASE_URL||'').replace(/\/$/,'');
const SUPABASE_ANON_KEY=String(process.env.SUPABASE_ANON_KEY||'');
const SUPABASE_SERVICE_ROLE_KEY=String(process.env.SUPABASE_SERVICE_ROLE_KEY||'');
const IS_PROD=process.env.NODE_ENV==='production';
const DATA_DIR=path.join(__dirname,'data');
const CHECKIN_PREFIX='RUNFLOW_DAILY_CHECKIN:';
const EVENT_PREFIX='RUNFLOW_LEARNING_EVENT:';

function parseCookies(req){const out={};String(req.headers.cookie||'').split(';').forEach(p=>{const i=p.indexOf('=');if(i<0)return;const k=p.slice(0,i).trim(),v=p.slice(i+1).trim();if(k)out[k]=decodeURIComponent(v)});return out}
function cookie(name,value,maxAge){return `${name}=${encodeURIComponent(value)}; Path=/; HttpOnly; SameSite=Lax${IS_PROD?'; Secure':''}; Max-Age=${maxAge}`}
function sendJson(res,status,data){const body=JSON.stringify(data);res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(body),'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(body)}
async function readJson(req){let body='';for await(const chunk of req){body+=chunk;if(body.length>1000000)throw Object.assign(new Error('Solicitud demasiado grande.'),{status:413})}if(!body)return{};try{return JSON.parse(body)}catch{throw Object.assign(new Error('JSON no válido.'),{status:400})}}
async function fetchJson(url,opt={}){const r=await fetch(url,opt),text=await r.text();let d=null;try{d=text?JSON.parse(text):null}catch{d=text}if(!r.ok){const msg=d&&typeof d==='object'?(d.message||d.error_description||d.error||d.details):d;throw Object.assign(new Error(msg||`HTTP ${r.status}`),{status:r.status,details:d})}return d}
async function sb(table,query='',opt={}){if(!SUPABASE_URL||!SUPABASE_SERVICE_ROLE_KEY)throw Object.assign(new Error('Supabase no está configurado.'),{status:503});const headers={apikey:SUPABASE_SERVICE_ROLE_KEY,Authorization:`Bearer ${SUPABASE_SERVICE_ROLE_KEY}`,...(opt.body!==undefined?{'Content-Type':'application/json'}:{}),...(opt.prefer?{Prefer:opt.prefer}:{})};return fetchJson(`${SUPABASE_URL}/rest/v1/${table}${query?`?${query}`:''}`,{method:opt.method||'GET',headers,body:opt.body===undefined?undefined:JSON.stringify(opt.body)})}
async function authUser(access){return fetchJson(`${SUPABASE_URL}/auth/v1/user`,{headers:{apikey:SUPABASE_ANON_KEY,Authorization:`Bearer ${access}`}})}
async function authRefresh(refresh){return fetchJson(`${SUPABASE_URL}/auth/v1/token?grant_type=refresh_token`,{method:'POST',headers:{apikey:SUPABASE_ANON_KEY,'Content-Type':'application/json'},body:JSON.stringify({refresh_token:refresh})})}
async function requireSession(req,res){const c=parseCookies(req);let access=c.rf_access,refresh=c.rf_refresh;if(!access)throw Object.assign(new Error('Debes iniciar sesión.'),{status:401});let user;try{user=await authUser(access)}catch{if(!refresh)throw Object.assign(new Error('Debes iniciar sesión.'),{status:401});const x=await authRefresh(refresh);access=x.access_token;refresh=x.refresh_token||refresh;user=x.user||await authUser(access);res.setHeader('Set-Cookie',[cookie('rf_access',access,Math.max(60,Number(x.expires_in)||3600)),cookie('rf_refresh',refresh,60*60*24*30)])}const [roles,athletes]=await Promise.all([sb('user_roles',`user_id=eq.${encodeURIComponent(user.id)}&select=role`),sb('athletes',`user_id=eq.${encodeURIComponent(user.id)}&lifecycle_status=eq.active&select=id&limit=1`)]);return{user,roles:roles.map(x=>x.role),athlete_id:athletes[0]?.id||null}}
function requireRole(s,role){if(!s.roles.includes(role))throw Object.assign(new Error('No tienes permiso para realizar esta acción.'),{status:403})}
async function ensureCoach(s,id){requireRole(s,'coach');const rows=await sb('coach_athletes',`coach_user_id=eq.${encodeURIComponent(s.user.id)}&athlete_id=eq.${encodeURIComponent(id)}&select=athlete_id&limit=1`);if(!rows.length)throw Object.assign(new Error('No tienes acceso a este deportista.'),{status:403})}
function text(v,max=5000){return String(v??'').trim().slice(0,max)}
function num(v,min,max){const n=Number(v);return Number.isFinite(n)&&n>=min&&n<=max?n:null}
function validDate(v){return /^\d{4}-\d{2}-\d{2}$/.test(String(v||''))?String(v):null}
function localDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:process.env.RUNFLOW_TIMEZONE||'Europe/Madrid',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function addDays(iso,n){const d=new Date(`${iso}T12:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function avg(a){const x=a.map(Number).filter(Number.isFinite);return x.length?Math.round((x.reduce((s,v)=>s+v,0)/x.length)*100)/100:null}
function parseTagged(row,prefix){const raw=String(row?.comment||'');if(!raw.startsWith(prefix))return null;try{return{...JSON.parse(raw.slice(prefix.length)),_id:row.id,_created_at:row.created_at}}catch{return null}}
async function learningRows(athleteId,limit=700){return sb('manual_session_logs',`athlete_id=eq.${encodeURIComponent(athleteId)}&workout_id=is.null&select=id,athlete_id,workout_id,rpe,comment,created_at&order=created_at.desc&limit=${Math.max(20,Math.min(1000,limit))}`).catch(()=>[])}
async function checkins(athleteId){const rows=await learningRows(athleteId,500);return rows.map(r=>parseTagged(r,CHECKIN_PREFIX)).filter(Boolean).sort((a,b)=>String(a.date).localeCompare(String(b.date)))}
function checkinStats(rows,today=localDate()){const prior=rows.filter(x=>x.date<today).map(x=>x.recovery_score),all=rows.map(x=>x.recovery_score),recent=rows.filter(x=>x.date>=addDays(today,-6)&&x.date<=today).map(x=>x.recovery_score),current=rows.find(x=>x.date===today)||null,baseline=avg(prior.length?prior:all);return{count:rows.length,baseline_mean:baseline,rolling_7_mean:avg(recent),today_score:current?.recovery_score??null,delta_vs_baseline:current&&baseline!==null?Math.round((Number(current.recovery_score)-baseline)*100)/100:null}}
async function getCheckinBundle(athleteId){const rows=await checkins(athleteId),today=localDate();return{today:rows.find(x=>x.date===today)||null,history:rows.slice(-90),stats:checkinStats(rows,today)}}
async function saveCheckin(athleteId,body){const score=num(body.recovery_score,1,5);if(score===null)throw Object.assign(new Error('La sensación de recuperación debe estar entre 1 y 5.'),{status:400});const date=validDate(body.date)||localDate(),payload={kind:'daily_checkin',date,recovery_score:score,comment:text(body.comment,1200)||'',source:'athlete',recorded_at:new Date().toISOString()},rows=await learningRows(athleteId,500),existing=rows.map(r=>({row:r,data:parseTagged(r,CHECKIN_PREFIX)})).find(x=>x.data?.date===date),record={rpe:score,comment:`${CHECKIN_PREFIX}${JSON.stringify(payload)}`,status:'completed',actual_duration_min:null,pain:null,feeling:null,pain_area:null,created_at:new Date().toISOString()};if(existing)await sb('manual_session_logs',`id=eq.${encodeURIComponent(existing.row.id)}&athlete_id=eq.${encodeURIComponent(athleteId)}`,{method:'PATCH',body:record,prefer:'return=minimal'});else await sb('manual_session_logs','',{method:'POST',body:{id:crypto.randomUUID(),athlete_id:athleteId,workout_id:null,...record},prefer:'return=minimal'});return getCheckinBundle(athleteId)}
async function saveLearningEvent(athleteId,coachUserId,body){const origin=['manual','imported','runflow_generated','ai_accepted','ai_modified'].includes(body.origin)?body.origin:'manual',event={kind:'planning_event',event_id:crypto.randomUUID(),recorded_at:new Date().toISOString(),coach_user_id:coachUserId,origin,entity_type:text(body.entity_type,80)||'planning',action:text(body.action,80)||'write',path:text(body.path,500),season_id:text(body.season_id,100)||null,context:body.context&&typeof body.context==='object'?body.context:{},payload:body.payload&&typeof body.payload==='object'?body.payload:{}};const encoded=`${EVENT_PREFIX}${JSON.stringify(event)}`.slice(0,12000);await sb('manual_session_logs','',{method:'POST',body:{id:crypto.randomUUID(),athlete_id:athleteId,workout_id:null,status:'completed',actual_duration_min:null,rpe:null,pain:null,feeling:null,pain_area:null,comment:encoded,created_at:event.recorded_at},prefer:'return=minimal'});return event}
async function events(athleteId){const rows=await learningRows(athleteId,900);return rows.map(r=>parseTagged(r,EVENT_PREFIX)).filter(Boolean).sort((a,b)=>String(a.recorded_at).localeCompare(String(b.recorded_at)))}
function libraryId(workout){for(const b of Array.isArray(workout?.blocks)?workout.blocks:[]){if(b&&b.type==='runflow_meta'&&b.library_id)return String(b.library_id)}return null}
async function learningSummary(athleteId){const newest=localDate(),oldest=addDays(newest,-180),[ci,ev,workouts,activities,logs,wellness]=await Promise.all([checkins(athleteId),events(athleteId),sb('workouts',`athlete_id=eq.${encodeURIComponent(athleteId)}&workout_date=gte.${oldest}&workout_date=lte.${newest}&select=*&order=workout_date.asc`).catch(()=>[]),sb('activities',`athlete_id=eq.${encodeURIComponent(athleteId)}&activity_date=gte.${oldest}T00:00:00&activity_date=lte.${newest}T23:59:59&select=*&order=activity_date.asc`).catch(()=>[]),sb('manual_session_logs',`athlete_id=eq.${encodeURIComponent(athleteId)}&workout_id=not.is.null&select=*&order=created_at.asc`).catch(()=>[]),sb('daily_metrics',`athlete_id=eq.${encodeURIComponent(athleteId)}&metric_date=gte.${oldest}&metric_date=lte.${newest}&select=*&order=metric_date.asc`).catch(()=>[])]);const ciBy=new Map(ci.map(x=>[x.date,x])),wellBy=new Map(wellness.map(x=>[x.metric_date,x])),actsBy=new Map(),logsBy=new Map();activities.forEach(a=>{if(a.workout_id){const k=String(a.workout_id);if(!actsBy.has(k))actsBy.set(k,[]);actsBy.get(k).push(a)}});logs.forEach(l=>{const k=String(l.workout_id);if(!logsBy.has(k))logsBy.set(k,[]);logsBy.get(k).push(l)});const episodes=workouts.map(w=>{const date=String(w.workout_date).slice(0,10),acts=actsBy.get(String(w.id))||[],ls=(logsBy.get(String(w.id))||[]).sort((a,b)=>String(b.created_at).localeCompare(String(a.created_at))),fb=ls[0]||null,actual={duration_min:acts.length?Math.round(acts.reduce((s,a)=>s+Number(a.duration_sec||0),0)/60):fb?.actual_duration_min??null,load:acts.length?Math.round(acts.reduce((s,a)=>s+Number(a.load||0),0)*10)/10:null,distance_km:acts.length?Math.round(acts.reduce((s,a)=>s+Number(a.distance_m||0),0)/100)/10:null,elevation_m:acts.length?Math.round(acts.reduce((s,a)=>s+Number(a.elevation_gain_m||0),0):null};return{date,workout_id:w.id,library_id:libraryId(w),planning:{title:w.title,sport:w.sport,priority:w.priority||null,planned_duration_min:w.planned_duration_min??null,planned_load:w.planned_load??null,session_objective:w.session_objective||null,adaptation_target:w.adaptation_target||null},pre_state:{subjective:ciBy.get(date)||null,objective:wellBy.get(date)||null},actual,feedback:fb?{rpe:fb.rpe,feeling:fb.feeling,pain:fb.pain,pain_area:fb.pain_area,comment:fb.comment,status:fb.status}:null,has_activity:acts.length>0}});return{range:{oldest,newest},checkins:{stats:checkinStats(ci,newest),count:ci.length},planning_events:{count:ev.length,by_origin:ev.reduce((o,e)=>(o[e.origin]=(o[e.origin]||0)+1,o),{}),recent:ev.slice(-40)},episodes:episodes.filter(x=>x.has_activity||x.feedback).slice(-180)}}

let libCache=null;
function isLongRun(s){const v=`${s.Nombre||''} ${s.Familia||''} ${s.Objetivo_primario||''}`.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();return /tirada larga|long run|larga aer[oó]bica|duracion larga/.test(v)}
function policySession(s){const original=Number(s.Tiempo_total_min);if(!Number.isFinite(original)||original<=60||isLongRun(s))return{...s,Tiempo_total_min_original:original||null,Politica_duracion_RunFlow:isLongRun(s)?'tirada_larga_exenta':'sin_ajuste'};const adjusted=60,rpe=Number(s.RPE_sesion_estimado);return{...s,Tiempo_total_min_original:original,Tiempo_total_min:adjusted,Carga_sRPE_est:Number.isFinite(rpe)?adjusted*rpe:s.Carga_sRPE_est,Politica_duracion_RunFlow:'max_60_no_tirada_larga',Nota_duracion_RunFlow:`Versión operativa RunFlow limitada a ${adjusted} min. La dosificación detallada debe respetar este máximo.`}}
function loadLibrary(){if(libCache)return libCache;let encoded='';const files=fs.readdirSync(DATA_DIR).filter(n=>/^runflow-v9-library\.part\d+\.b64$/.test(n)).sort((a,b)=>Number(a.match(/part(\d+)/)[1])-Number(b.match(/part(\d+)/)[1]));encoded=files.map(n=>fs.readFileSync(path.join(DATA_DIR,n),'utf8').trim()).join('');if(!encoded)throw Object.assign(new Error('Biblioteca V9 no disponible.'),{status:503});const compact=JSON.parse(zlib.gunzipSync(Buffer.from(encoded,'base64')).toString('utf8')),keyMap={i:'ID',n:'Nombre',d:'Disciplina',f:'Familia',o:'Objetivo_primario',ph:'Fases',g:'Objetivos_prueba',lv:'Nivel_1_5',tm:'Tiempo_total_min',wu:'Calentamiento',bp:'Bloque_principal',cd:'Vuelta_calma',int:'Intensidad_prescrita',r:'RPE_sesion_estimado',ter:'Terreno',e:'Desnivel_requerido',mat:'Material',rec:'Recuperacion_recomendada_h',pr:'Progresion_anterior_ID',nx:'Progresion_siguiente_ID',cg:'Grupo_comparacion',cmp:'Comparabilidad',sel:'Condiciones_seleccion',no:'No_usar_si',ok:'Criterio_exito',adj:'Regla_ajuste',l:'Carga_sRPE_est',lr:'Carga_relativa_1_5'},raw=(compact.s||[]).map(row=>Object.fromEntries(Object.entries(row).map(([k,v])=>[keyMap[k]||k,v]))),sessions=raw.map(policySession),adjusted=sessions.filter(x=>x.Politica_duracion_RunFlow==='max_60_no_tirada_larga').length,band45=sessions.filter(x=>!isLongRun(x)&&Number(x.Tiempo_total_min)>=40&&Number(x.Tiempo_total_min)<=50).length,band60=sessions.filter(x=>!isLongRun(x)&&Number(x.Tiempo_total_min)>50&&Number(x.Tiempo_total_min)<=60).length;libCache={version:'Biblioteca RunFlow de Sesiones v1.1 · política de duración',sessions,policy:{non_long_max_minutes:60,long_runs_exempt:true,selection_target_bands:[45,60],adjusted_sessions:adjusted,band_45_count:band45,band_60_count:band60}};return libCache}

async function handle(req,res,url){const p=url.pathname,method=req.method||'GET',isLearning=p.startsWith('/api/v2/athlete/daily-checkin')||p.includes('/learning-event')||p.includes('/learning-events')||p.includes('/learning-summary')||p.includes('/daily-checkins')||p==='/api/v9/library';if(!isLearning)return false;const s=await requireSession(req,res);if(p==='/api/v9/library'&&method==='GET'){requireRole(s,'coach');const lib=loadLibrary();sendJson(res,200,{...lib,count:lib.sessions.length});return true}if(p==='/api/v2/athlete/daily-checkin'){requireRole(s,'athlete');if(!s.athlete_id)throw Object.assign(new Error('Tu usuario no está vinculado a un deportista.'),{status:409});if(method==='GET'){sendJson(res,200,await getCheckinBundle(s.athlete_id));return true}if(method==='POST'){sendJson(res,201,await saveCheckin(s.athlete_id,await readJson(req)));return true}}let m=p.match(/^\/api\/v9\/coach\/athletes\/([^/]+)\/daily-checkins$/);if(m&&method==='GET'){const id=decodeURIComponent(m[1]);await ensureCoach(s,id);sendJson(res,200,await getCheckinBundle(id));return true}m=p.match(/^\/api\/v9\/coach\/athletes\/([^/]+)\/learning-event$/);if(m&&method==='POST'){const id=decodeURIComponent(m[1]);await ensureCoach(s,id);sendJson(res,201,{event:await saveLearningEvent(id,s.user.id,await readJson(req))});return true}m=p.match(/^\/api\/v9\/coach\/athletes\/([^/]+)\/learning-events$/);if(m&&method==='GET'){const id=decodeURIComponent(m[1]);await ensureCoach(s,id);sendJson(res,200,{events:await events(id)});return true}m=p.match(/^\/api\/v9\/coach\/athletes\/([^/]+)\/learning-summary$/);if(m&&method==='GET'){const id=decodeURIComponent(m[1]);await ensureCoach(s,id);sendJson(res,200,await learningSummary(id));return true}return false}

const nativeCreateServer=http.createServer;
http.createServer=function runflowLearningCreateServer(listener){return nativeCreateServer.call(http,async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||'localhost'}`);try{if(await handle(req,res,url))return}catch(error){console.error('[learning-hook]',error);return sendJson(res,Number(error.status||500),{error:error.message||'Error interno.',details:error.details||null})}return listener(req,res)})};
